name: SkyBlock
version: '${project.version}'
main: de.iplexy.skyblock.SkyBlock
api-version: 1.19
authors: [ iPlexy ]
description: SkyBlock - System
website: https://iplexy.de
depend:
  - SlimeWorldManager
commands:
  Spawn:
  Island:
    aliases:
      - is
      - sb
      - skyblock
      - insel
